# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.chatTemplateConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm.fullname" . }}-chat-templates
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  tool_chat_template_qwen3coder.jinja: |-
{{ .Files.Get "files/tool_chat_template_qwen3coder.jinja" | indent 4 }}
  tool_chat_template_hermes.jinja: |-
{{ .Files.Get "files/tool_chat_template_hermes.jinja" | indent 4 }}
{{- end }}
